#!/usr/local/sbin/charm-env python3

from charmhelpers.core import hookenv
from charmhelpers.core.unitdata import kv
from charms import layer
from reactive import snap


layer.import_layer_libs()


try:
    # ensure /snap/bin is on the path
    snap.ensure_path()

    service_accounts = layer.gcp._gcloud('iam', 'service-accounts', 'list')
    account_keys = kv().getrange('charm.gcp.account-keys.', strip=True)

    active = {key['service-account'] for key in account_keys.values()}
    unknown = {sa['email'] for sa in service_accounts
               if sa['email'].startswith('juju-gcp-')} - active

    # TODO remove dead SAs from project policy
    for service_account in unknown:
        layer.gcp._gcloud('iam', 'service-accounts', 'delete', service_account)
        layer.gcp.log('Deleted service account {}', service_account)

    hookenv.action_set({
        'purged': ', '.join(unknown),
    })
except layer.gcp.GCPError as e:
    hookenv.action_fail(str(e))
